#！/usr/bin/env python
#-*- coding:utf-8 -*-
# {
# 'disk':{
# 'status':True,
# 'error':'',
# 'data':{
# '0':{},
# '1':{},
# '2':{},
# '3':{},
# '4':{},
# '5':{}
# }
# },
# 'memory':{},
# 'basic':{
# 'status':True,
# 'error':'',
# 'data':{
# 'os_platform':'linux',
# 'os_version':'6.5',
# 'hostname':'c1.com'
# }
# },
# 'cpu':{
# 'status':True,
# 'error':'',
# 'data':{
# 'cpu_count':24,
# 'cpu_physical_count':2,
# 'cpu_model':' Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz'
# }
# },
# 'main_board':{
# 'status':True,
# 'error':'',
# 'data':{}
# }
# }